# Generated by Django 4.2.24 on 2025-10-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='tenant',
        ),
    ]
