# Generated by Django 4.2.24 on 2025-10-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryledger',
            old_name='Ingredient_id',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purchase_id',
            new_name='purchase',
        ),
    ]
