# Generated by Django 4.2.24 on 2025-10-12 23:43

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_ingredient_id_inventoryledger_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date_time',
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',            
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
