# Generated by Django 4.2.24 on 2025-10-11 14:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_date_time', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recipes.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCostSheetOtherCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('metrix_system_unit', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('recipe_cost_sheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.recipecostsheet')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCostSheetOtherCostsIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchases.ingredient')),
                ('recipe_cost_sheet_other_costs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.recipecostsheetothercosts')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCostSheetIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('Ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchases.ingredient')),
                ('recipe_cost_sheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculations.recipecostsheet')),
            ],
        ),
    ]
