# Generated by Django 4.2.24 on 2025-10-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecostsheet',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='recipecostsheetingredient',
            old_name='Ingredient_id',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='recipecostsheetingredient',
            old_name='recipe_cost_sheet_id',
            new_name='recipe_cost_sheet',
        ),
        migrations.RenameField(
            model_name='recipecostsheetothercosts',
            old_name='recipe_cost_sheet_id',
            new_name='recipe_cost_sheet',
        ),
        migrations.RenameField(
            model_name='recipecostsheetothercostsingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipecostsheetothercostsingredient',
            old_name='recipe_cost_sheet_other_costs_id',
            new_name='recipe_cost_sheet_other_costs',
        ),
    ]
