INSERT INTO purchases_ingredient (name) VALUES
('Farinha de trigo'),
('Açúcar refinado'),
('Açúcar mascavo'),
('Açúcar de confeiteiro'),
('Cacau em pó'),
('Manteiga'),
('Margarina'),
('Óleo vegetal'),
('Óleo de girassol'),
('Ovos'),
('Claras de ovo'),
('Fermento em pó'),
('Bicarbonato de sódio'),
('Essência de baunilha'),
('Leite condensado'),
('Leite em pó integral'),
('Leite em pó desnatado'),
('Chocolate meio amargo'),
('Chocolate ao leite'),
('Chocolate branco'),
('Gotas de chocolate'),
('Amido de milho'),
('Mel'),
('Xarope de milho'),
('Sal'),
('Fermento biológico seco'),
('Gelatina em pó sem sabor'),
('Agar-agar'),
('Creme de leite'),
('Cream cheese'),
('Mascarpone'),
('Ricota'),
('Iogurte natural'),
('Suco de limão'),
('Raspas de limão'),
('Raspas de laranja'),
('Coco ralado'),
('Flocos de coco'),
('Pasta de amendoim'),
('Farinha de amêndoas'),
('Farinha de avelã'),
('Farinha de aveia'),
('Farinha de arroz'),
('Geleia de morango'),
('Geleia de framboesa'),
('Geleia de damasco'),
('Corante alimentício'),
('Baunilha em fava'),
('Canela em pó'),
('Noz-moscada'),
('Essência de amêndoas');
