# Generated by Django 4.2.24 on 2025-10-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient_id',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
