# Generated by Django 4.2.24 on 2025-10-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichacusto',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fichacustoinsumo',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fichacustooutroscustos',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fichacustooutroscustos_insumo',
            name='tenant',
        ),
    ]
