# Generated by Django 4.2.24 on 2025-10-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='compraitem',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fichakardex',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tenant',
        ),
    ]
