INSERT INTO purchases_supplier (name) VALUES
('Casa das Farinhas'),
('Açucareira Paulista'),
('Laticínios Serra Azul'),
('Cacau Nobre Distribuidora'),
('Manteigueira do Vale'),
('Óleos & Sabores Brasil'),
('Grãos do Sul Atacadista'),
('Doce Brasil Importadora'),
('Confeitaria & Cia Suprimentos'),
('Aromas da Baunilha'),
('Mundo do Chocolate'),
('Distribuidora Santo Trigo'),
('Essências e Corantes Real'),
('CremoLeite Alimentos'),
('Doces da Serra Comercial'),
('Panifícios União Fornecimentos'),
('Sabor Mineiro Atacado'),
('Delícias do Norte Distribuidora'),
('Açúcar & Cacau Premium'),
('Bom Gosto Suprimentos'),
('Imperial Ingredientes'),
('Rio Doce Representações'),
('Nobre Alimentos e Insumos'),
('Flor de Coco Distribuição'),
('Cereais do Campo'),
('Culinária Fina Fornecedores'),
('Misturas & Fermentos Brasil'),
('Soluções para Panificação'),
('Leve Sabor Atacadista'),
('Sabores do Lar Comercial'),
('Alfa Insumos Alimentícios'),
('Chef Confeiteiro Suprimentos'),
('Delica Pan Atacado'),
('Nordeste Distribuidora de Alimentos'),
('Sul Pan Insumos'),
('Mar & Terra Temperos'),
('Açúcar Real Comercial'),
('Baunilha & Canela Fornecimentos'),
('Cacau do Cerrado'),
('Bella Massa Ingredientes'),
('Master Pan Distribuição'),
('Top Confeitaria Atacado'),
('Sabor Nobre Alimentos'),
('Rota dos Grãos Comércio'),
('Doçaria Nacional Suprimentos'),
('Prime Ingredientes Brasil'),
('Qualipan Distribuidora'),
('Ponto do Confeiteiro'),
('Gran Chef Fornecedores'),
('Panin House Insumos');
